project:
  type: website

website:
  title: "Quarto Test for Global Include"
  navbar:
    left:
      - href: index.qmd
        text: Home
  sidebar:
    contents: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



